#!/usr/bin/env bash

findcpu(){
  findcpu_tmp="$(grep 'model name' /proc/cpuinfo  | uniq)"
  echo "${findcpu_tmp//model[[:space:]]name[[:space:]]:[[:space:]]/}"
}

findgpu(){
 nvidia-smi --query-gpu name --format=csv,noheader -i 0
}

findcputemperature(){
  findcputemperature_tmp=$(sensors | grep -i "Tctl:")
	echo "${findcputemperature_tmp//Tctl:[[:space:]]*+/}"
}

findgputemperature(){
	findgputemperature_tmp=$(nvidia-smi --query-gpu temperature.gpu --format=csv,noheader -i 0)
	echo "${findgputemperature_tmp}.0°C"
}
 
totalmem(){
  totalmem_tmp="$(grep -i 'memtotal' /proc/meminfo)"
  totalmem_tmp="${totalmem_tmp//[^[:digit:]]}"
	echo "$((totalmem_tmp/1024/1024))" GB
}

vram() {
  vram_tmp=$(nvidia-smi --query-gpu memory.total --format=csv,noheader -i 0)
  vram_tmp="${vram_tmp//[[:space:]]*MiB}"
  echo $((vram_tmp/1024)) GB

}



echo \
"              .,-:;//;:=,                 $(tput smso)  Aperture Science Terminal Info                        $(tput rmso)
          . :H@@@MM@M#H/.,+%;,             $(tput bold)CPU Model:$(tput sgr0) $(findcpu) 
       ,/X+ +M@@M@MM%=,-%HMMM@X/,          $(tput bold)Total RAM:$(tput sgr0) $(totalmem)
     -+@MM; SM@@MH+-,;XMMMM@MMMM@+-        $(tput bold)CPU Temp:$(tput sgr0) $(findcputemperature) 
    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.      
  =@#@@@MX .,              -%HXSS%%%+;     $(tput bold)GPU Model:$(tput sgr0) $(findgpu) 
 =-./@M@MS                  .;@MMMM@MM:    $(tput bold)Total VRAM:$(tput sgr0) $(vram)
 X@/ -SMM/                    .+MM@@@MS    $(tput bold)GPU Temp:$(tput sgr0) $(findgputemperature)
,@M@H: :@:                    . =X#@@@@-   
,@@@MMX, .                    /H- ;@M@M=  $(tput smso)  GLaDOS Monitor                                        $(tput rmso)
.H@@@@M@+,                    %MM+..%#S.                                 ____ 
 /MMMM@MMH/.                  XM@MH; =;    $(tput bold)System status:$(tput sgr0)  On           /   /
  /%+%SXHH@S=              , .H@@@@MX,     $(tput bold)Voice status:$(tput sgr0)   On     ___  /   /
   .=--------.           -%H.,@@@@@MX,                            \  \/   /
    .%MM@@@HHHXXSSS%+- .:MMX =M@@MM%.      $(tput bold)Damaged:       $(tput sgr0) No      \     /
     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=        $(tput bold)Malfunctioning:$(tput sgr0) Maybe    \___/ 
       =%@M@M#@S-.=S@MM@@@M; %M%=           
         ':+S+-,/H#MMMMMMM@= ='            
               =++%%%%+/:-.                
"
