#!/bin/bash

findcpu(){
	grep 'model name' /proc/cpuinfo  | uniq | awk -F':' '{ print $2}'
}

findgpu(){
 nvidia-smi --query-gpu name --format=csv,noheader -i 0
}
 
findcputemperature(){
	sensors | grep -i "Tctl:" | sed "s/Tctl:[[:space:]]*+//i"
}

findgputemperature(){
	nvidia-smi --query-gpu temperature.gpu --format=csv,noheader -i 0
}
 
totalmem(){
	grep -i 'memtotal' /proc/meminfo | awk -F':' '{ print $2}'
}

vram=$(nvidia-smi --query-gpu memory.total --format=csv,noheader -i 0 | sed "s/[[:space:]]*MiB//i")
mem=$(cat /proc/meminfo | grep MemTotal | head -n 1 | awk '/[0-9]/ {print $2}')


echo \
"              .,-:;//;:=,                 `tput smso`  Aperture Science Terminal Info                        `tput rmso`
          . :H@@@MM@M#H/.,+%;,             `tput bold`CPU Model:`tput sgr0` $(findcpu) 
       ,/X+ +M@@M@MM%=,-%HMMM@X/,          `tput bold`Total RAM:`tput sgr0` $[($mem/1024)/1024] GB
     -+@MM; SM@@MH+-,;XMMMM@MMMM@+-        `tput bold`CPU Temp:`tput sgr0` $(findcputemperature) 
    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.      
  =@#@@@MX .,              -%HXSS%%%+;     `tput bold`GPU Model:`tput sgr0` $(findgpu) 
 =-./@M@MS                  .;@MMMM@MM:    `tput bold`Total VRAM:`tput sgr0` $[$vram/1024] GB
 X@/ -SMM/                    .+MM@@@MS    `tput bold`GPU Temp:`tput sgr0` $(findcputemperature)
,@M@H: :@:                    . =X#@@@@-   
,@@@MMX, .                    /H- ;@M@M=  `tput smso`  GLaDOS Monitor                                        `tput rmso`
.H@@@@M@+,                    %MM+..%#S.                                 ____ 
 /MMMM@MMH/.                  XM@MH; =;    `tput bold`System status:`tput sgr0`  On           /   /
  /%+%SXHH@S=              , .H@@@@MX,     `tput bold`Voice status:`tput sgr0`   On     ___  /   /
   .=--------.           -%H.,@@@@@MX,                            \  \/   /
    .%MM@@@HHHXXSSS%+- .:MMX =M@@MM%.      `tput bold`Damaged:       `tput sgr0` No      \     /
     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=        `tput bold`Malfunctioning:`tput sgr0` Maybe    \___/ 
       =%@M@M#@S-.=S@MM@@@M; %M%=           
         ':+S+-,/H#MMMMMMM@= ='            
               =++%%%%+/:-.                
"
