#!/usr/bin/env bash
cd /home/jimmy/.local/share/Discord || exit
./Discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy
