#! /bin/bash
shopt -s extglob
OIFS="$IFS"
IFS=$(echo -en "\n\b")
if [ ! -d "$1" ]; then
	echo "ERROR:"
	echo "$1 is not a directory..."
	exit
fi
JMN_TEMP_DIRECTORY="${1%%+(/)}"
while :
do
	if [ ! -e "$JMN_TEMP_DIRECTORY" ]; then
		break
	fi
	JMN_TEMP_DIRECTORY="$JMN_TEMP_DIRECTORY""_"
done
echo "Using $JMN_TEMP_DIRECTORY as temporary directory name..."
if [ -d "$1" ]; then 
	DIRECTORIES=$(find "$1" -type d)
	for D in $DIRECTORIES
	do
		if [ ! -h "$D" ]; then
			mkdir -pv "$JMN_TEMP_DIRECTORY/$(realpath -s --relative-to="$1" "$D")"/
			chattr +F "$JMN_TEMP_DIRECTORY/$(realpath -s --relative-to="$1" "$D")"/
		fi
	done
	FILES=$(find "$1" -type f)
	for F in $FILES
	do
		if [ ! -h "$F" ]; then
			mv -v "$F" "$JMN_TEMP_DIRECTORY/$(realpath -s --relative-to="$1" "$F")"
		fi
	done
	LINKS=$(find "$1" -type l)
	for L in $LINKS
	do
		mv -v "$L" "$JMN_TEMP_DIRECTORY/$(realpath -s --relative-to="$1" "$L")"
	done
	find "$1" -type d -empty -delete
fi

if ! [ -e "$1" ]; then 
	mv -v "$JMN_TEMP_DIRECTORY" "$1"
	echo "SUCCESS:"
	echo "Task Complete..."
elif [ -e "$1" ]; then 
	echo "ERROR:"
	echo "Something went wrong with the process..."
fi
IFS="$OIFS"
