#!/usr/bin/env bash

if [ -n "${JMN_UPDATE+x}" ]; then
	clear
	cd "$HOME/Repos/Games/gamma-launcher/easy-install" || exit
	make PREFIX="${HOME}/.local" uninstall
	make PREFIX="${HOME}/.local" clean
	cd "../" || exit
	do_git_pull .
	cd "./easy-install" || exit
	make "-j$(nproc)"
	make PREFIX="${HOME}/.local" install
fi

clear
"$(which gamma-launcher)" "$@"