#!/usr/bin/env bash
APPID="359320"
SteamAppId="359320"
if [ -z "${SteamAppId+x}" ]; then
	if [ -n "${APPID+x}" ]; then
		SteamAppId="$APPID"
	elif [ -z "${APPID+x}" ]; then
		SteamAppId="0"
	fi
fi
if [ -z "${WINEDLLOVERRIDES+x}" ]; then
	WINEDLLOVERRIDES="winemenubuilder.exe=d"
elif [ -n "${WINEDLLOVERRIDES+x}" ]; then
	WINEDLLOVERRIDES="${WINEDLLOVERRIDES};winemenubuilder.exe=d"
fi
if [ -z "${APPID+x}" ]; then
	if [ -n "${SteamAppId+x}" ]; then
		APPID="$SteamAppId"
	fi
fi
if [ "$APPID" == 0 ]; then
	UMU_STEAM_GAME_ID="$APPID"
	STORE="none"
	GAMEID="umu-default"
elif [ "$APPID" != 0 ]; then
	UMU_STEAM_GAME_ID="$APPID"
	STORE="steam"
	GAMEID="umu-$APPID"
fi
if [ -z "${WINE_DEBUG_DIR+x}" ]; then
	WINE_DEBUG_DIR="$HOME/Games/__Apps__/Wine-Cache"
fi
if ! [ -d "${WINE_DEBUG_DIR}" ]; then
	if [ -e "${WINE_DEBUG_DIR}" ]; then
		rm -rf "$WINE_DEBUG_DIR"
	fi
	echo WINE_DEBUG_DIR
	mkdir -p "$WINE_DEBUG_DIR"
fi
if [ -z "${DXVK_FILTER_DEVICE_NAME+x}" ]; then
	DXVK_FILTER_DEVICE_NAME="NVIDIA GeForce RTX 3060"
fi
if [ -z "${STEAM_COMPAT_DATA_PATH+x}" ]; then
	STEAM_COMPAT_DATA_PATH="$WINE_DEBUG_DIR/compatdata/$SteamAppId"
fi
if ! [ -d "${STEAM_COMPAT_DATA_PATH}" ]; then
	if [ -e "${STEAM_COMPAT_DATA_PATH}" ]; then
		rm -rf "$STEAM_COMPAT_DATA_PATH"
	fi
	echo STEAM_COMPAT_DATA_PATH
	mkdir -p "$STEAM_COMPAT_DATA_PATH"
fi
if [ -z "${SDL_VIDEODRIVER+x}" ]; then
	SDL_VIDEODRIVER="windows,wayland,x11"
fi
if [ -z "${JMN_NOPRELOAD+x}" ]; then
	JMN_NOPRELOAD="1"
fi
if [ "$JMN_NOPRELOAD" = "1" ] || [ "$JMN_NOPRELOAD" = "true" ] || [ "$JMN_NOPRELOAD" = "yes" ]; then
	LD_PRELOAD=""
fi
if [ -z "${JMN_LSFG+x}" ]; then
	JMN_LSFG="1"
fi
if [ "$JMN_LSFG" = "1" ] || [ "$JMN_LSFG" = "true" ] || [ "$JMN_LSFG" = "yes" ]; then
	LSFG_PROCESS="LSFG-VK Injected Game"
fi
if [ -z "${JMN_LOCAL_PROTON+x}" ]; then
	JMN_LOCAL_PROTON="0"
fi
if [ "$JMN_LOCAL_PROTON" = "1" ] || [ "$JMN_LOCAL_PROTON" = "true" ] || [ "$JMN_LOCAL_PROTON" = "yes" ]; then
	PROTON_VERSION="$(< "${STEAM_COMPAT_DATA_PATH}/version" sed -n 1p)"
	PROTONCOMPATPATH="$HOME/.local/share/Steam/compatibilitytools.d/$PROTON_VERSION"
fi
if [ -z "${JMN_DXVK+x}" ]; then
	JMN_DXVK="1"
fi
if [ -z "${JMN_DXVK_CONF+x}" ]; then
	JMN_DXVK_CONF="1"
fi
if [ -z "${JMN_EXPLORER+x}" ]; then
	JMN_EXPLORER="0"
fi
if [ -z "${JMN_NODLSSSWAP+x}" ]; then
	JMN_NO_DLSS_SWAP="0"
fi
if [ -z "${JMN_MANGOHUD+x}" ]; then
	JMN_MANGOHUD="0"
fi
if [ -z "${JMN_NODECORATE+x}" ]; then
	JMN_NODECORATE="0"
fi
if [ -z "${JMN_NONGX+x}" ]; then
	JMN_NONGX="0"
fi
if [ -z "${JMN_NONVAPI+x}" ]; then
	JMN_NONVAPI="0"
fi
if [ -z "${JMN_NOSYNC+x}" ]; then
	JMN_NOSYNC="0"
fi
if [ -z "${JMN_SDL+x}" ]; then
	JMN_SDL="0"
fi
if [ -z "${JMN_WEMOD+x}" ]; then
	JMN_WEMOD="0"
fi
if [ -z "${JMN_ZINK+x}" ]; then
	JMN_ZINK="0"
fi
if [ -z "${JMN_DECK+x}" ]; then
	JMN_DECK="0"
fi
if [ -z "${JMN_NOFSR4UP+x}" ]; then
	JMN_NOFSR4UP="0"
fi
if [ "$JMN_NOFSR4UP" = "1" ] || [ "$JMN_NOFSR4UP" = "true" ] || [ "$JMN_NOFSR4UP" = "yes" ]; then
	PROTON_FSR4_UPGRADE="0"
fi
if [ -z "${PROTON_FSR4_UPGRADE+x}" ]; then
	PROTON_FSR4_UPGRADE="1"
fi
if [ -z "${JMN_32+x}" ]; then
	JMN_32="0"
fi
if [ "$JMN_32" = "1" ] || [ "$JMN_32" = "true" ] || [ "$JMN_32" = "yes" ]; then
	PROTON_USE_WOW64="1"
fi
if [ -z "${PROTON_USE_WOW64+x}" ]; then
	PROTON_USE_WOW64="0"
fi
if [ -z "${JMN_NONTSYNC+x}" ]; then
	JMN_NONTSYNC="0"
fi
if [ "$JMN_NONTSYNC" = "1" ] || [ "$JMN_NONTSYNC" = "true" ] || [ "$JMN_NONTSYNC" = "yes" ]; then
	PROTON_USE_NTSYNC="0"
fi
if [ -z "${PROTON_USE_NTSYNC+x}" ]; then
	PROTON_USE_NTSYNC="1"
fi
if [ "$JMN_SDL" = "1" ] || [ "$JMN_SDL" = "true" ] || [ "$JMN_SDL" = "yes" ]; then
	PROTON_PREFER_SDL_INPUT="1"
	WINE_PREFER_SDL_INPUT="1"
fi
if [ "$JMN_NODECORATE" = "1" ] || [ "$JMN_NODECORATE" = "true" ] || [ "$JMN_NODECORATE" = "yes" ]; then
	PROTON_NO_WM_DECORATION="1"
	WINE_NO_WM_DECORATION="1"
fi
if [ -z "${UMU_NO_RUNTIME+x}" ]; then
	UMU_NO_RUNTIME="1"
fi
if [ -z "${UMU_RUNTIME_UPDATE+x}" ]; then
	UMU_RUNTIME_UPDATE="1"
fi
#if [ -z "${PROTON_VERB+x}" ]; then
#	PROTON_VERB="waitforexitandrun"
#fi
if [ -z "${JMN_EXEC+x}" ]; then
	if ! [ -f "$(which gamemoderun)" ] && [ -f "$(which game-performance)" ]; then
		JMN_EXEC=("game-performance" "$@")
	elif [ -f "$(which gamemoderun)" ] && [ -f "$(which game-performance)" ]; then
		JMN_EXEC=("game-performance" "$@")
	elif [ -f "$(which gamemoderun)" ] && ! [ -f "$(which game-performance)" ]; then
		JMN_EXEC=("gamemoderun" "$@")
	elif ! [ -f "$(which gamemoderun)" ] && ! [ -f "$(which game-performance)" ]; then
		JMN_EXEC=("$@")
	fi
elif [ -n "${JMN_EXEC+x}" ]; then
	JMN_EXEC=("${JMN_EXEC[@]}" "$@")
fi
if [ "$JMN_NODLSSSWAP" != "1" ] && [ "$JMN_NODLSSSWAP" != "true" ] && [ "$JMN_NODLSSSWAP" != "yes" ]; then
	JMN_EXEC=("dlss-swapper" "${JMN_EXEC[@]}")
fi
if [ "$JMN_MANGOHUD" = "1" ] || [ "$JMN_MANGOHUD" = "true" ] || [ "$JMN_MANGOHUD" = "yes" ]; then
	JMN_EXEC=("mangohud" "${JMN_EXEC[@]}")
fi
if [ "$JMN_WEMOD" = "1" ] || [ "$JMN_WEMOD" = "true" ] || [ "$JMN_WEMOD" = "yes" ]; then
	pushd "$HOME/Repos/Games/wemod-launcher/" || return
	git stash
	git pull
	git stash pop
	chmod -R ug+x .
	popd || return
	JMN_EXEC=("$HOME/Repos/Games/wemod-launcher/wemod" "${JMN_EXEC[@]}")
fi
if [ "$JMN_DECK" = "1" ] || [ "$JMN_DECK" = "true" ] || [ "$JMN_DECK" = "yes" ]; then
	SteamDeck="1"
fi
if [ -z "${JMN_DXVK_CONFIG+x}" ]; then
	JMN_DXVK_CONFIG="d3d11.maxFeatureLevel=12_1:d3d9.dpiAware=True:d3d9.maxAvailableMemory=12160:d3d9.shaderModel=3:dxgi.maxDeviceMemory=12160"
elif [ -n "${JMN_DXVK_CONFIG+x}" ]; then
	JMN_DXVK_CONFIG="${JMN_DXVK_CONFIG}:d3d11.maxFeatureLevel=12_1:d3d9.dpiAware=True:d3d9.maxAvailableMemory=12160:d3d9.shaderModel=3:dxgi.maxDeviceMemory=12160"
fi
if [ "$JMN_DXVK_CONF" = "1" ] || [ "$JMN_DXVK_CONF" = "true" ] || [ "$JMN_DXVK_CONF" = "yes" ]; then
	DXVK_CONFIG="$HOME/Games/wine/dxvk.conf"
fi
if [ "$JMN_ZINK" = "1" ] || [ "$JMN_ZINK" = "true" ] || [ "$JMN_ZINK" = "yes" ]; then
	__GLX_VENDOR_LIBRARY_NAME="mesa"
	GALLIUM_DRIVER="zink"
	MESA_LOADER_DRIVER_OVERRIDE="zink"
fi
if [ "$JMN_EXPLORER" = "1" ] || [ "$JMN_EXPLORER" = "true" ] || [ "$JMN_EXPLORER" = "yes" ]; then
	PROTON_REMOTE_DEBUG_CMD="$HOME/Games/__Tools__/Explorer++/Explorer++.exe"
fi
if [ -z "${LOG_DIR+x}" ]; then
	LOG_DIR="$WINE_DEBUG_DIR/logs/$SteamAppId"
fi
if ! [ -d "${LOG_DIR}" ]; then
	if [ -e "${LOG_DIR}" ]; then
		rm -rf "$LOG_DIR"
	fi
	echo LOG_DIR
	mkdir -p "$LOG_DIR"
fi
if [ -z "${SCRIPT_DIR+x}" ]; then
	SCRIPT_DIR="$HOME/Games/wine/"
fi
if ! [ -d "${SCRIPT_DIR}" ]; then
	if [ -e "${SCRIPT_DIR}" ]; then
		rm -rf "$SCRIPT_DIR"
	fi
	echo SCRIPT_DIR
	mkdir -p "$SCRIPT_DIR"
fi
if [ -z "${WINECOMPATPATH+x}" ]; then
	if [ -z "${WINEPATH+x}" ]; then
		WINECOMPATPATH="/opt/wine-cachyos"
		if [ -d "${WINECOMPATPATH}" ]; then
			if [ -z "${WINE+x}" ]; then
				WINE="$WINECOMPATPATH/bin/wine"
			fi
			if [ -z "${WINE64+x}" ]; then
				WINE64="$WINECOMPATPATH/bin/wine64"
			fi
			if [ -z "${WINESERVER+x}" ]; then
				WINESERVER="$WINECOMPATPATH/bin/wineserver"
			fi
			if [ -z "${WINEBOOT+x}" ]; then
				WINEBOOT="$WINECOMPATPATH/bin/wineboot"
			fi
			if [ -z "${WINELOADER+x}" ]; then
				if [ -f "${WINE64+x}" ]; then
					WINELOADER="$WINE64"
				elif ! [ -f "${WINE64+x}" ]; then
					if [ -f "${WINE+x}" ]; then
						WINELOADER="$WINE"
					fi
				fi
			fi
		fi
	elif [ -n "${WINEPATH+x}" ]; then
		WINECOMPATPATH="$WINEPATH"
	fi
fi
if [ -z "${WINEPATH+x}" ]; then
	WINEPATH="$WINECOMPATPATH"
fi
if [ -n "${WINEPREFIX+x}" ]; then
	WINEPREFIXTMP="$WINEPREFIX"
elif [ -z "${WINEPREFIX+x}" ]; then
	WINEPREFIXTMP="$STEAM_COMPAT_DATA_PATH/pfx"
	WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx"
fi
if ! [ -d "${WINEPREFIX}" ]; then
	if [ -e "${WINEPREFIX}" ]; then
		rm -rf "$WINEPREFIX"
	fi
	echo WINEPREFIX
	mkdir -p "$WINEPREFIX"
fi
if [ -z "${STEAM_COMPAT_SHADER_PATH+x}" ]; then
	STEAM_COMPAT_SHADER_PATH="$(realpath -q "$STEAM_COMPAT_DATA_PATH/../../shadercache/$SteamAppId")"
	if ! [ -d "${STEAM_COMPAT_SHADER_PATH}" ]; then
		if [ -e "${STEAM_COMPAT_SHADER_PATH}" ]; then
			rm -rf "$STEAM_COMPAT_SHADER_PATH"
		fi
		echo STEAM_COMPAT_SHADER_PATH
		mkdir -p "$STEAM_COMPAT_SHADER_PATH"
	fi
fi
if [ -d "${STEAM_COMPAT_SHADER_PATH}" ]; then
	if [ -z "${__GL_SHADER_DISK_CACHE_PATH+x}" ]; then
		__GL_SHADER_DISK_CACHE_PATH="$STEAM_COMPAT_SHADER_PATH/nvidiav1"
	fi
	if [ -z "${AMD_VK_PIPELINE_CACHE_PATH+x}" ]; then
		AMD_VK_PIPELINE_CACHE_PATH="$STEAM_COMPAT_SHADER_PATH/AMDv1"
	fi
	if [ -z "${DXVK_STATE_CACHE_PATH+x}" ]; then
		DXVK_STATE_CACHE_PATH="$STEAM_COMPAT_SHADER_PATH/DXVK_state_cache"
	fi
	if [ -z "${MESA_GLSL_CACHE_DIR+x}" ]; then
		MESA_GLSL_CACHE_DIR="$STEAM_COMPAT_SHADER_PATH"
	fi
	if [ -z "${MESA_SHADER_CACHE_DIR+x}" ]; then
		MESA_SHADER_CACHE_DIR="$STEAM_COMPAT_SHADER_PATH"
	fi
	if [ -z "${VKD3D_SHADER_CACHE_PATH+x}" ]; then
		VKD3D_SHADER_CACHE_PATH="$STEAM_COMPAT_SHADER_PATH/VKD3D_state_cache"
	fi
fi
if [ -d "${WINECOMPATPATH}" ]; then
	if [ -z "${WINE+x}" ]; then
		WINE="$(find "$WINECOMPATPATH" -type f -wholename "*/bin/wine")"
	fi
	if [ -z "${WINE64+x}" ]; then
		WINE64="$(find "$WINECOMPATPATH" -type f -wholename "*/bin/wine64")"
	fi
	if [ -z "${WINESERVER+x}" ]; then
		WINESERVER="$(find "$WINECOMPATPATH" -type f -wholename "*/bin/wineserver")"
	fi
	if [ -z "${WINEBOOT+x}" ]; then
		WINEBOOT="$(find "$WINECOMPATPATH" -type f -wholename "*/bin/wineboot")"
	fi
	if [ -z "${WINELOADER+x}" ]; then
		if [ -f "${WINE64+x}" ]; then
			WINELOADER="$WINE64"
		elif ! [ -f "${WINE64+x}" ]; then
			if [ -f "${WINE+x}" ]; then
				WINELOADER="$WINE"
			fi
		fi
	fi
fi
if [ -z "${DXVK_PATH+x}" ]; then
	DXVK_PATH="/usr/share/dxvk/"
fi
if [ "$JMN_NONVAPI" != "1" ] && [ "$JMN_NONVAPI" != "true" ] && [ "$JMN_NONVAPI" != "yes" ]; then
	PROTON_DISABLE_NVAPI="0"
	PROTON_ENABLE_NVAPI="1"
	PROTON_FORCE_NVAPI="1"
	PROTON_HIDE_NVIDIA_GPU="0"
fi
if [ "$JMN_NOSYNC" != "1" ] && [ "$JMN_NOSYNC" != "true" ] && [ "$JMN_NOSYNC" != "yes" ]; then
	PROTON_NO_ESYNC="0"
	PROTON_NO_FSYNC="0"
	WINEESYNC="1"
	WINEFSYNC="1"
fi
if [ "$JMN_NONGX" != "1" ] && [ "$JMN_NONGX" != "true" ] && [ "$JMN_NONGX" != "yes" ]; then
	PROTON_ENABLE_NGX_UPDATER="1"
fi
if [ -z "${__GL_SHADER_DISK_CACHE_SKIP_CLEANUP+x}" ]; then
	__GL_SHADER_DISK_CACHE_SKIP_CLEANUP="1"
fi
if [ -z "${__GL_SHADER_DISK_CACHE+x}" ]; then
	__GL_SHADER_DISK_CACHE="1"
fi
if [ -z "${__GL_THREADED_OPTIMIZATIONS+x}" ]; then
	__GL_THREADED_OPTIMIZATIONS="1"
fi
if [ -z "${DXVK_ASYNC+x}" ]; then
	DXVK_ASYNC="1"
fi
if [ -z "${DXVK_GPLASYNCCACHE+x}" ]; then
	DXVK_GPLASYNCCACHE="1"
fi
if [ -z "${DXVK_HUD+x}" ]; then
	DXVK_HUD="compiler"
elif [ -n "${DXVK_HUD+x}" ]; then
	DXVK_HUD="${DXVK_HUD},compiler"
fi
if [ -z "${DXVK_LOG_LEVEL+x}" ]; then
	DXVK_LOG_LEVEL="none"
fi
if [ -z "${DXVK_LOG_PATH+x}" ]; then
	DXVK_LOG_PATH="none"
fi
if [ -z "${DXVK_NVAPI_ALLOW_OTHER_DRIVERS+x}" ]; then
	DXVK_NVAPI_ALLOW_OTHER_DRIVERS="1"
fi
if [ -z "${DXVK_NVAPI_DRIVER_VERSION+x}" ]; then
	DXVK_NVAPI_DRIVER_VERSION="47141"
fi
if [ -z "${DXVK_NVAPI_LOG_LEVEL+x}" ]; then
	DXVK_NVAPI_LOG_LEVEL="none"
fi
if [ -z "${DXVK_STATE_CACHE+x}" ]; then
	DXVK_STATE_CACHE="1"
fi
if [ -z "${PROTON_DUMP_DEBUG_COMMANDS+x}" ]; then
	PROTON_DUMP_DEBUG_COMMANDS="1"
fi
if [ -z "${PROTON_FORCE_LARGE_ADDRESS_AWARE+x}" ]; then
	PROTON_FORCE_LARGE_ADDRESS_AWARE="1"
fi
if [ -z "${PROTON_LOG+x}" ]; then
	PROTON_LOG="0"
fi
if [ -z "${PROTON_SET_GAME_DRIVE+x}" ]; then
	PROTON_SET_GAME_DRIVE="1"
fi
if [ -z "${PROTON_USE_XALIA+x}" ]; then
	PROTON_USE_XALIA="0"
fi
if [ -z "${RADV_PERFTEST+x}" ]; then
	RADV_PERFTEST="gpl"
elif [ -n "${RADV_PERFTEST+x}" ]; then
	RADV_PERFTEST="${RADV_PERFTEST},gpl"
fi
if [ -z "${VK_ICD_FILENAMES+x}" ] && [ -z "${container+x}" ]; then
	VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
fi
if [ -z "${VKD3D_CONFIG+x}" ]; then
	VKD3D_CONFIG="dxr11,dxr"
elif [ -n "${VKD3D_CONFIG+x}" ]; then
	VKD3D_CONFIG="${VKD3D_CONFIG},dxr11,dxr"
fi
if [ -z "${VKD3D_FEATURE_LEVEL+x}" ]; then
	VKD3D_FEATURE_LEVEL="12_2"
fi
if [ -z "${WINE_FULLSCREEN_INTEGER_SCALING+x}" ]; then
	WINE_FULLSCREEN_INTEGER_SCALING="1"
fi
if [ -z "${VKD3D_SHADER_MODEL+x}" ]; then
	VKD3D_SHADER_MODEL="6_7"
fi
if [ -z "${WINE_CPU_TOPOLOGY+x}" ]; then
	WINE_CPU_TOPOLOGY="7:1,2,3,4,5,6,7"
fi
if [ -z "${WINEDEBUG+x}" ]; then
	WINEDEBUG="-all"
fi
if [ -z "${WINE_SIMULATE_WRITECOPY+x}" ]; then
	WINE_SIMULATE_WRITECOPY="1"
fi
if ! [ -d "${MESA_SHADER_CACHE_DIR}" ]; then
	if [ -e "${MESA_SHADER_CACHE_DIR}" ]; then
		rm -rf "$MESA_SHADER_CACHE_DIR"
	fi
	echo MESA_SHADER_CACHE_DIR
	mkdir -p "$MESA_SHADER_CACHE_DIR"
fi
if ! [ -d "${MESA_GLSL_CACHE_DIR}" ]; then
	if [ -e "${MESA_GLSL_CACHE_DIR}" ]; then
		rm -rf "$MESA_GLSL_CACHE_DIR"
	fi
	echo MESA_GLSL_CACHE_DIR
	mkdir -p "$MESA_GLSL_CACHE_DIR"
fi
if ! [ -d "${STEAM_COMPAT_SHADER_PATH}" ]; then
	if [ -e "${STEAM_COMPAT_SHADER_PATH}" ]; then
		rm -rf "$STEAM_COMPAT_SHADER_PATH"
	fi
	echo STEAM_COMPAT_SHADER_PATH
	mkdir -p "$STEAM_COMPAT_SHADER_PATH"
fi
if ! [ -d "${AMD_VK_PIPELINE_CACHE_PATH}" ]; then
	if [ -e "${AMD_VK_PIPELINE_CACHE_PATH}" ]; then
		rm -rf "$AMD_VK_PIPELINE_CACHE_PATH"
	fi
	echo AMD_VK_PIPELINE_CACHE_PATH
	mkdir -p "$AMD_VK_PIPELINE_CACHE_PATH"
fi
if ! [ -d "${__GL_SHADER_DISK_CACHE_PATH}" ]; then
	if [ -e "${__GL_SHADER_DISK_CACHE_PATH}" ]; then
		rm -rf "$__GL_SHADER_DISK_CACHE_PATH"
	fi
	echo __GL_SHADER_DISK_CACHE_PATH
	mkdir -p "$__GL_SHADER_DISK_CACHE_PATH"
fi
if ! [ -d "${DXVK_STATE_CACHE_PATH}" ]; then
	if [ -e "${DXVK_STATE_CACHE_PATH}" ]; then
		rm -rf "$DXVK_STATE_CACHE_PATH"
	fi
	echo DXVK_STATE_CACHE_PATH
	mkdir -p "$DXVK_STATE_CACHE_PATH"
fi
if ! [ -d "${VKD3D_SHADER_CACHE_PATH}" ]; then
	if [ -e "${VKD3D_SHADER_CACHE_PATH}" ]; then
		rm -rf "$VKD3D_SHADER_CACHE_PATH"
	fi
	echo VKD3D_SHADER_CACHE_PATH
	mkdir -p "$VKD3D_SHADER_CACHE_PATH"
fi
WINEPREFIXDRIVEC="$WINEPREFIX/drive_c"
appendwinepath() {
	case ":$WINEDLLPATH:" in
		*:"$1":*)
			;;
		*)
			WINEDLLPATH="${WINEDLLPATH:+$WINEDLLPATH:}$1"
	esac
}
if [ "${WINEDLLPATH}" != "$HOME/.local/lib/discord-rpc-wine/x86_64:$HOME/.local/lib/discord-rpc-wine/i686" ]; then
	if [ -d "$HOME/.local/lib/discord-rpc-wine/x86_64" ]; then
		appendwinepath "$HOME/.local/lib/discord-rpc-wine/x86_64"
	fi
	if [ -d "$HOME/.local/lib/discord-rpc-wine/i686" ]; then
		appendwinepath "$HOME/.local/lib/discord-rpc-wine/i686"
	fi
	if [ -d "$HOME/.local/lib/discord-rpc-wine/i686" ] || [ -d "$HOME/.local/lib/discord-rpc-wine/x86_64" ]; then
		if [ -z "${WINEDLLOVERRIDES+x}" ]; then
			WINEDLLOVERRIDES="discord-rpc=b"
		elif [ -n "${WINEDLLOVERRIDES+x}" ]; then
			WINEDLLOVERRIDES="${WINEDLLOVERRIDES};discord-rpc=b"
		fi
	fi
fi
fixwineprefix() {
	${WINEBOOT} -u
	if [ -d "${WINEPREFIXDRIVEC}" ]; then
		echo "Current Target Prefix Is $WINEPREFIXDRIVEC"
		if [ -L "$WINEPREFIXDRIVEC/users" ]; then
			echo "Removing Target Link $WINEPREFIXDRIVEC/users"
			unlink "$WINEPREFIXDRIVEC/users"
		fi
		if [ -L "$WINEPREFIXDRIVEC/windows/temp" ]; then
			echo "Removing Target Link Is $WINEPREFIXDRIVEC/windows/temp"
			unlink "$WINEPREFIXDRIVEC/windows/temp"
		fi
		if [ -d "$WINEPREFIXDRIVEC/users" ]; then
			if [ ! -h "$WINEPREFIXDRIVEC/users" ]; then
				echo "Removing Target Directory Is $WINEPREFIXDRIVEC/users"
				rm -rvfd "$WINEPREFIXDRIVEC/users"
			fi
		fi
		if [ -d "$WINEPREFIXDRIVEC/windows/temp" ]; then
			if [ ! -h "$WINEPREFIXDRIVEC/windows/temp" ]; then
				echo "Removing Target Directory Is $WINEPREFIXDRIVEC/windows/temp"
				rm -rvfd "$WINEPREFIXDRIVEC/windows/temp"
			fi
		fi
		if ! [ -e "$WINEPREFIXDRIVEC/users" ]; then
			echo "Creating Target Link Is $WINEPREFIXDRIVEC/users"
			ln -svf "$HOME/Games/__Userdata__/users/" "$WINEPREFIXDRIVEC/users"
		fi
		if ! [ -e "$WINEPREFIXDRIVEC/windows/temp" ]; then
			echo "Creating Target Link $WINEPREFIXDRIVEC/windows/temp"
			ln -svf "/tmp/" "$WINEPREFIXDRIVEC/windows/temp"
		fi
		echo Wine Path Is "$WINECOMPATPATH"
		echo Wine Executable Is "$WINE"
		echo Wine Server Executable Is "$WINESERVER"
		# shellcheck disable=SC2153
		if [ "$JMN_DXVK" = "1" ] || [ "$JMN_DXVK" = "true" ] || [ "$JMN_DXVK" = "yes" ]; then
			/usr/share/dxvk/setup_dxvk.sh install
		fi
		if [ ! -d "$STEAM_COMPAT_INSTALL_PATH/x" ]; then
			if [ -e "$STEAM_COMPAT_INSTALL_PATH/x" ]; then
				rm -rf "$STEAM_COMPAT_INSTALL_PATH/x"
			fi
			winestreamproxy-install
		fi
	fi
} &> "$LOG_DIR/prep.log"
if [ -e "${STEAM_COMPAT_DATA_PATH}" ] && [ -e "${WINEPREFIX}" ]; then
	{
		printenv -0 | sort -f -z | tr '\0' '\n'
	} > "$LOG_DIR/environment.list"
	fixwineprefix
	cp -f -s -t "$SCRIPT_DIR" "$LOG_DIR/environment.list" "$LOG_DIR/prep.log"
fi
pushd "${WINEPREFIXDRIVEC}/users/jimmy/AppData/Local/EDHM-UI-V3" || exit
"${WINE}" "${WINEPREFIXDRIVEC}/users/jimmy/AppData/Local/EDHM-UI-V3/EDHM-UI-V3.exe"























































































































