#!/usr/bin/env bash
export LD_PRELOAD_TMP="$LD_PRELOAD"
export LD_PRELOAD=""
if [[ -z "${JMN_DEFAULT_APPID+x}" ]]; then
	export JMN_DEFAULT_APPID="EDHM-UI"
fi
if [[ -z "${JMN_DEFAULT_COMPAT_ROOT+x}" ]]; then
	export JMN_DEFAULT_COMPAT_ROOT="Wine"
fi
if [[ -z "${PROTONCOMPATPATH+x}" ]]; then
	if [[ -z "${PROTONPATH+x}" ]]; then
		export PROTONCOMPATPATH="/opt/wine-cachyos"
	fi
fi
if [[ -z "${STEAM_COMPAT_DATA_PATH+x}" ]]; then
	if [[ -n "${WINEPREFIX+x}" ]]; then
		export STEAM_COMPAT_DATA_PATH="$WINEPREFIX"
	fi
fi
if [[ -z "${WINEPREFIX+x}" ]]; then
	export WINEPREFIX="$STEAM_COMPAT_DATA_PATH"
fi
if [[ -z "${PROTON_DEBUG_DIR+x}" ]]; then
	export PROTON_DEBUG_DIR="$HOME/Games/__Apps__/Wine-Cache"
fi
source environment-wine-general
JMN_EXECUTABLE_DIR="${WINEPREFIXDRIVEC}/users/jimmy/AppData/Local/EDHM-UI-V3"
export JMN_EXEC_TMP=("${JMN_EXEC[@]}" "$WINE" "${JMN_EXECUTABLE_DIR}/EDHM-UI-V3.exe" "${@:-${@}}")
export JMN_EXEC=("${JMN_EXEC_TMP[@]}")
unset JMN_EXEC_TMP
if ! [[ -d "${LOG_DIR}" ]]; then
	if [[ -e "${LOG_DIR}" ]]; then
		rm -rfv "$LOG_DIR"
	fi
	echo LOG_DIR
	mkdir -pv "$LOG_DIR"
fi
touch "$LOG_DIR/prep.log"
truncate -s 0 "$LOG_DIR/prep.log"
jmn_create_directories &>> "$LOG_DIR/prep.log"
if [[ -z "${JMN_WATCH_LOG+x}" ]]; then
	export JMN_WATCH_LOG="0"
fi
if [[ "$JMN_WATCH_LOG" = "1" ]] || [[ "$JMN_WATCH_LOG" = "true" ]] || [[ "$JMN_WATCH_LOG" = "yes" ]]; then
	{
		echo "Watching log file at \"$LOG_DIR/prep.log\""
		echo "Press [CTRL+C] to stop."
		echo ""
	 } >> "$LOG_DIR/prep.log"
	alacritty --title "Game Output" --command tail --silent --follow=name --lines=+1 "$LOG_DIR/prep.log" &
fi
pushd "${JMN_EXECUTABLE_DIR}" || exit
echo "${JMN_EXEC[@]}" &>> "$LOG_DIR/prep.log"
export LD_PRELOAD="$LD_PRELOAD_TMP"
("${JMN_EXEC[@]}") &>> "$LOG_DIR/prep.log"
environment-unset
