#!/usr/bin/env bash

# shellcheck disable=SC2034
LD_PRELOAD=""
ED_DIR="$HOME/Repos/Elite-Dangerous"
# shellcheck disable=SC2154
EDMC_PLUGINS="$XDG_DATA_HOME/EDMarketConnector/plugins"
EDMC_DIR="$ED_DIR/EDMarketConnector"
EDMC_DATA_DIR="$XDG_DATA_HOME/EDMarketConnector"
TMPDIR="${EDMC_DIR}/tmp"

mkdir -p "${TMPDIR}"

if [ -n "${JMN_UPDATE+x}" ]; then 
	do_git_pull "$ED_DIR/BioScan"
	do_git_pull "$ED_DIR/ExploData"
	do_git_pull "$ED_DIR/NavRoute"
	do_git_pull "$ED_DIR/Pioneer"
	do_git_pull "$ED_DIR/EDMC_SpanshRouter"
	do_git_pull "$ED_DIR/EDMC-Canonn"
	do_git_pull "$ED_DIR/EDMC-Discord-Presence"
	do_git_pull "$ED_DIR/EDMC-FuelStatus"
	do_git_pull "$ED_DIR/LandingPad"
	do_git_pull "$EDMC_DIR" "stable"
	SOLUTION_FILES="$(find "$EDMC_PLUGINS" "$ED_DIR" -type f -name "*.sln")"
	for F in $SOLUTION_FILES
	do
		nuget restore "$F"
	done
	mkdir -p "$EDMC_DATA_DIR"
	cd "$EDMC_DATA_DIR" || exit
	pyenv install --skip-existing "$(cat "${EDMC_DIR}/.python-version")"
	pyenv local "$(cat "${EDMC_DIR}/.python-version")"
fi

eval "$(pyenv init - zsh)"
python3 -m venv Python
# shellcheck disable=SC3046
# shellcheck disable=SC3051
# shellcheck disable=SC1091
source "$EDMC_DATA_DIR/Python/bin/activate"

if [ -n "${JMN_UPDATE+x}" ]; then
	python3 -m pip install pip
	python3 -m pip install --upgrade pip
	python3 -m pip install playsound3
	python3 -m pip install --upgrade playsound3
	python3 -m pip install tcl
	python3 -m pip install --upgrade tcl
	python3 -m pip install tk
	python3 -m pip install --upgrade tk
	python3 -m pip install -r "$EDMC_PLUGINS/EDMCModernOverlay/overlay_client/requirements/base.txt"
	python3 -m pip install -r "$EDMC_PLUGINS/EDMCModernOverlay/overlay_client/requirements/wayland.txt"
	REQUIREMENTS_FILES="$(find "$EDMC_PLUGINS" "$ED_DIR" -type f -name "*requirements.txt")"
	for F in $REQUIREMENTS_FILES
	do
		python3 -m pip install -r "$F"
	done
	chmod +x -R "$EDMC_PLUGINS"
	chmod +x -R "$ED_DIR"
fi

pushd "$EDMC_DIR" || exit
python3 EDMarketConnector.py




