#!/usr/bin/env bash
export LD_PRELOAD_TMP="$LD_PRELOAD"
export LD_PRELOAD=""
read_runner() {
	orig_nocasematch=$(shopt -p nocasematch; true)
	local orig_nocasematch
	orig_nullglob=$(shopt -p nullglob; true)
	local orig_nullglob
	local OIFS="$IFS"
	shopt -s nocasematch
	shopt -s nullglob
	IFS=$'\n'
	while IFS= read -r line
	do
		# shellcheck disable=SC2001
		if [[ "${line,,}" =~ ^runnertype=.*$ ]]
		then
			RUNNER_TYPE="$(echo "$line" | sed 's/^runnertype=//i')"
			export RUNNER_TYPE
		fi
		# shellcheck disable=SC2001
		if [[ "${line,,}" =~ ^protonversion=.*$ ]]
		then
			PROTON_VERSION="$(echo "$line" | sed 's/^protonversion=//i')"
			export PROTON_VERSION
		fi
		# shellcheck disable=SC2001
		if [[ "${line,,}" =~ ^wineversion=.*$ ]]
		then
			WINE_VERSION="$(echo "$line" | sed 's/^wineversion=//i')"
			export WINE_VERSION
		fi
	done < "$HOME/.xlcore/launcher.ini"
	$orig_nocasematch
	$orig_nullglob
	local IFS="$OIFS"
}
read_runner
if [[ "$RUNNER_TYPE" == "Proton" ]]; then
	export PROTONCOMPATPATH="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/compatibilitytools.d/$PROTON_VERSION"
	export STEAM_COMPAT_DATA_PATH="$HOME/.xlcore/protonprefix"
	export WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx/"
fi
if [[ "$RUNNER_TYPE" == "Managed" ]]; then
	export PROTONCOMPATPATH="$HOME/.xlcore/compatibilitytool/wine/$WINE_VERSION"
	export STEAM_COMPAT_DATA_PATH="$HOME/.xlcore/wineprefix"
	export WINEPREFIX="$STEAM_COMPAT_DATA_PATH"
fi
export LD_PRELOAD="$LD_PRELOAD_TMP"
environment-proton "${@:-${@}}"
environment-unset
