#!/usr/bin/env bash
export LD_PRELOAD_TMP="$LD_PRELOAD"
export LD_PRELOAD=""
if [[ -z "${JMN_DEFAULT_APPID+x}" ]]; then
    export JMN_DEFAULT_APPID="0"
fi
if [[ -z "${JMN_DEFAULT_COMPAT_ROOT+x}" ]]; then
    export JMN_DEFAULT_COMPAT_ROOT="Steam-Other"
fi
if [[ -z "${PROTONCOMPATPATH+x}" ]]; then
	if [[ -z "${PROTONPATH+x}" ]]; then
		export PROTONCOMPATPATH="/usr/share/steam/compatibilitytools.d/proton-ge-custom"
	fi
fi
if [[ -z "${STEAM_COMPAT_DATA_PATH+x}" ]]; then
	if [[ -n "${WINEPREFIX+x}" ]]; then
		STEAM_COMPAT_DATA_PATH="$(realpath -q "$WINEPREFIX/..")"
		export STEAM_COMPAT_DATA_PATH
	fi
fi
if [[ -z "${WINEPREFIX+x}" ]]; then
	export WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx"
fi
if [[ -z "${PROTON_DEBUG_DIR+x}" ]]; then
	export PROTON_DEBUG_DIR="$HOME/Games/__Apps__/Proton-Cache"
fi
source environment-wine-general
if ! [[ -d "${LOG_DIR}" ]]; then
	if [[ -e "${LOG_DIR}" ]]; then
		rm -rfv "$LOG_DIR"
	fi
	echo LOG_DIR
	mkdir -pv "$LOG_DIR"
fi
touch "$LOG_DIR/prep.log"
truncate -s 0 "$LOG_DIR/prep.log"
jmn_create_directories &>> "$LOG_DIR/prep.log"
if [[ -z "${JMN_WATCH_LOG+x}" ]]; then
	export JMN_WATCH_LOG="0"
fi
if [[ "$JMN_WATCH_LOG" = "1" ]] || [[ "$JMN_WATCH_LOG" = "true" ]] || [[ "$JMN_WATCH_LOG" = "yes" ]]; then
	{
		echo "Watching log file at \"$LOG_DIR/prep.log\""
		echo "Press [CTRL+C] to stop."
		echo ""
	 } >> "$LOG_DIR/prep.log"
	alacritty --title "Game Output" --command tail --silent --follow=name --lines=+1 "$LOG_DIR/prep.log" &
fi
export LD_PRELOAD="$LD_PRELOAD_TMP"
echo "${JMN_EXEC[@]}" &>> "$LOG_DIR/prep.log"
("${JMN_EXEC[@]}") &>> "$LOG_DIR/prep.log"
environment-unset
