#!/usr/bin/env bash
export LD_PRELOAD_TMP="$LD_PRELOAD"
export LD_PRELOAD=""
if [[ -n "${INST_MC_DIR+x}" ]]; then
    do_git_pull "$INST_MC_DIR/resourcepacks/GTNH-Faithful-Textures"
fi
export LD_PRELOAD="$LD_PRELOAD_TMP"
environment-minecraft "${@:-${@}}"
environment-unset