#!/usr/bin/env bash
export LD_PRELOAD_TMP="$LD_PRELOAD"
export LD_PRELOAD=""
if [[ -z "${DATA_DIR_NAME+x}" ]]; then
	if [[ -f "$(which "${1}" 2>/dev/null)" ]]; then
		DATA_DIR_NAME="$(basename "$(which "${1}" 2>/dev/null)")"
		export DATA_DIR_NAME
	else
		export DATA_DIR_NAME="default"
	fi
fi
source environment-native-general
[[ -n "${LOG_DIR}" ]] && jmn_function_create_directory "${LOG_DIR}"
touch "$LOG_DIR/prep.log"
truncate -s 0 "$LOG_DIR/prep.log"
jmn_full_setup &>> "$LOG_DIR/prep.log"
echo "${JMN_EXEC[@]}" &>> "$LOG_DIR/prep.log"
export LD_PRELOAD="$LD_PRELOAD_TMP"
("${JMN_EXEC[@]}") &>> "$LOG_DIR/prep.log"
environment-unset