#!/usr/bin/env bash
HOME_DIR="/home/jimmy"
SCRIPT_DIR=$HOME_DIR/Repos/Misc/nvidia-patch
SCRIPT_PATH="$SCRIPT_DIR/tools/patch-tester"
CACHE_DIR="$HOME_DIR/.cache/nvidia-patch"
LOG_PATH="$CACHE_DIR/test.log"
backup_path="$CACHE_DIR/backups"


if ! [ -e "$CACHE_DIR" ]
then
    mkdir -p $CACHE_DIR
elif [ -f  "$CACHE_DIR" ]
then
    rm "$LOG_PATH"
fi

if [ -f "$LOG_PATH" ]
then
    rm "$LOG_PATH"
elif [ -d "$LOG_PATH" ]
then
    rm -rfv "$LOG_PATH"
fi

{
      if [ -d "$SCRIPT_DIR" ]
      then
            do_git_pull "$SCRIPT_DIR" "master"
      fi
      "$SCRIPT_PATH/patch-tester.sh"
} 2>&1 | tee "$LOG_PATH"
