#!/usr/bin/env bash
shopt -s nullglob

OIFS="$IFS"
IFS=$'\n'

DIRECTORIES=$(find "$1" -type d)
for D in $DIRECTORIES
do
	mkdir -p "$2"/"$(realpath -s --relative-to="$1" "$D")"
done

FILES=$(find "$1" -type f)
for F in $FILES
do
	ln -sf "$F" "$2"/"$(realpath -s --relative-to="$1" "$F")"
done

IFS="$OIFS"
