#!/usr/bin/env bash
CHECK_ERROR_CODE() {
    if [[ "$1" != 0 ]]; then
        echo "ERROR: $2 exited with error code $1"
        exit 1
    elif [[ "$1" == 0 ]]; then
        echo "SUCCESS: $2 exited with error code $1"
    fi
}
export NVM_DIR="$HOME/.config/nvm"
# shellcheck disable=SC1091
source "$NVM_DIR/nvm.sh"  # This loads nvm
# shellcheck disable=SC1091
source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
pamac install mesa gtk3 gtk fuse2 fuse3 base-devel
CHECK_ERROR_CODE "$?" "pamac install mesa gtk3 gtk fuse2 fuse3 base-devel"
rm -rf "$HOME"/.cache/tauri/*
CHECK_ERROR_CODE "$?" "rm -rf $HOME/.cache/tauri/*"
cd "$HOME/Repos/Misc/iloader" || exit
CHECK_ERROR_CODE "$?" "cd $HOME/Repos/Misc/iloader"
do_git_pull ./
CHECK_ERROR_CODE "$?" "do_git_pull ./"
nvm install lts/krypton
CHECK_ERROR_CODE "$?" "nvm install lts/krypton"
nvm use 24
CHECK_ERROR_CODE "$?" "nvm use 24"
npm install -g bun
CHECK_ERROR_CODE "$?" "npm install -g bun"
bun i --frozen-lockfile
CHECK_ERROR_CODE "$?" "bun i --frozen-lockfile"
WEBKIT_DISABLE_COMPOSITING_MODE=1 GDK_BACKEND=x11 bun run tauri build
chmod -R +x ./
CHECK_ERROR_CODE "$?" "chmod -R +x ./"